server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/authdb
    username: postgres
    password: '@Srinani7029'
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

jwt:
  secret: 'G2!nQ9zT$eR7uLpVxY3bW6cD!@aM4zZ8'
  expiration: 86400000
